### ISSUE TITLE
more options

### ISSUE THREAD

**Issue by ctf0** [ejabu/vscode-file-shortcut#1]
is it possible to add new options like "add current file to list" instead of manual adding paths to the config.

also maybe an activity bar icon would be faaaar more intuitive than the status bar or the quick list.

**Comment by ejabu** [comment]
I think its good idea.

Related to your second idea, unfortunately I haven't try Activity Bar icon, could not imagine whether it is possible to open "Quick Open List" from those buttons..

**Comment by ctf0** [comment]
the activity bar is a replacement for the quick input.

**Comment by ctf0** [comment]
i worked on this today & i've actually made lots of changes to ur ext that i think it should be on its own.

still many thanx for the inspiration.
